---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages_to_install }}"

- name: Deploy custom index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Create a message of the day file
  ansible.builtin.copy:
    content: "This server is managed by Ansible.\nWelcome, {{ your_name }}!\n"
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  when: create_motd == true

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
