---
- name: Install NGINX and Deploy Custom Web Page
  hosts: all
  become: yes

  vars:
    page_title: "Ansible Deployed Site"
    welcome_message: "Welcome to Our Automated Web Server!"
    your_name: "Varun"
    packages_to_install:
      - nginx
      - git
      - tree

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages_to_install }}"

    - name: Deploy custom index.html from template
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
